name: Test, Build and Upload artifact

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Java 8 build, deliver artifact and container
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup PostgreSQL
        uses: huaxk/postgis-action@v1
        with:
          postgresql password: "postgres"
          postgresql user: "postgres"
          postgresql db: 'advanced_programing_project_user_DB'

      - name: Test and build project
        run: mvn -f pom.xml clean install

      - name: Show contents of the current working directory
        run: ls -la

      - name: Show contents of the target directory
        run: ls -la target

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: users-service-artifact.jar
          path: ./target/users-service-0.0.1-SNAPSHOT.jar

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/users-service-ex:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/users-service-ex:latest
